services:
  consul:
    build:
      context: ./services/discovery
      dockerfile: Dockerfile
    ports:
      - "8500:8500"
    command: "agent -dev -client=0.0.0.0"

  game:
    build: 
      context: ./services/game
      dockerfile: Dockerfile
    ports:
      - "5111:5111"
    environment:
      - DATABASE_URL=${DATABASE_URL_GAME}
      - REDIS_URL=${REDIS_URL}
    depends_on:
      - game-db
      - redis
  game-db: 
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_GAMES}
    volumes:
      - game-db-data:/var/lib/postgresql/data
      - ./services/game/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  users:
    build: 
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - DATABASE_URL=${DATABASE_URL_USERS}
    depends_on:
      - users-db
  users-db: 
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_USERS}
    volumes:
      - users-db-data:/var/lib/postgresql/data
      - ./services/users/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - game
      - users
  
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"  

volumes:
  game-db-data:
  users-db-data: