services:
  game:
    build: 
      context: ./services/game
      dockerfile: Dockerfile
    ports:
      - "5111:5111"
    environment:
      - DATABASE_URL=postgresql://admin:qwerty@game-db:5432/db-games
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - game-db
      - redis

  game-db: 
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db-games 
    volumes:
      - game-db-data:/var/lib/postgresql/data
      - ./services/game/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql

  users:
    build: 
      context: ./services/users
      dockerfile: Dockerfile
    ports:
      - "5000:5000" 
    environment:
      - DATABASE_URL=postgresql://admin:qwerty@users-db:5432/db-users
    depends_on:
      - users-db
  
  users-db: 
    image: postgres:13
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: qwerty
      POSTGRES_DB: db-users
    volumes:
      - users-db-data:/var/lib/postgresql/data
      - ./services/users/db/db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
  
  gateway:
    build:
      context: ./gateway
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - game
      - users
  
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"

volumes:
  game-db-data:
  users-db-data: