FROM consul:1.15.4

COPY consul-health-check.json /consul/config/consul-health-check.json 
COPY users-consul-config.json /consul/config/users-consul-config.json
COPY game-consul-config.json /consul/config/game-consul-config.json